# Prod environment overrides

replicaCount: 2

image:
  tag: "prod-5ac7b67a288921df4da6cf27fa448a9e3e81ac95"

autoscaling:
  enabled: true
  minReplicas: 2
  maxReplicas: 5

gateway:
  certificateArn: "arn:aws:acm:ap-south-1:796197769514:certificate/d52286ef-3e36-405d-84ee-8962ef43fb00"
  wafAclArn: "arn:aws:wafv2:ap-south-1:796197769514:regional/webacl/uplatform-waf/d9a4769d-7814-4e84-bef2-ffbf5f6a7591"
  host: jp2op-project.site

  publicSubnets:
    - subnet-05ea02d1974e207ab
    - subnet-0377323d11546e9c8
