# PROD environment overrides

replicaCount: 2

image:
  tag: "prod-latest"

resources:
  requests:
    cpu: 100m
    memory: 128Mi
  limits:
    cpu: 500m
    memory: 256Mi

autoscaling:
  enabled: true
  minReplicas: 2
  maxReplicas: 5

gateway:
  certificateArn: "arn:aws:acm:ap-south-1:796197769514:certificate/181167ae-42b0-4c0d-b80c-d05eed6e999c"
  wafAclArn: "arn:aws:wafv2:ap-south-1:796197769514:regional/webacl/uplatform-waf/10fd1896-84fe-4f51-a7f2-d215c4c2b595"
  host: jp2op-project.site
