# QA environment overrides

replicaCount: 1

image:
  tag: "latest"

autoscaling:
  enabled: true
  minReplicas: 1
  maxReplicas: 3

gateway:
  certificateArn: "arn:aws:acm:ap-south-1:796197769514:certificate/45b574b2-10dc-43ef-91c7-c19d8161bdb1"
  wafAclArn: "arn:aws:wafv2:ap-south-1:796197769514:regional/webacl/uplatform-waf/cc2e5397-d75c-4ddc-a93e-e9940fdbca3e"
  host: qa.jp2op-project.site
