# Prod environment overrides

replicaCount: 2

image:
  tag: "prod-latest"

autoscaling:
  enabled: true
  minReplicas: 2
  maxReplicas: 5

gateway:
  certificateArn: "arn:aws:acm:ap-south-1:796197769514:certificate/ecdb468c-53a6-447c-a9e7-30a35a9e8823"
  wafAclArn: "arn:aws:wafv2:ap-south-1:796197769514:regional/webacl/uplatform-waf/ca9f4d3d-cc20-470e-891b-da07f624544c"
  host: jp2op-project.site

  publicSubnets:
    - subnet-0c360b141c9612b03
    - subnet-0d709d3f2067af71e
