# QA environment overrides

replicaCount: 1

image:
  tag: "sha-399c149eb065d5a7b627973812cbe2e5a92336df"

autoscaling:
  enabled: true
  minReplicas: 1
  maxReplicas: 3

gateway:
  certificateArn: "arn:aws:acm:ap-south-1:796197769514:certificate/5b525c9f-0be5-4419-a6be-18400a9358d8"
  wafAclArn: "arn:aws:wafv2:ap-south-1:796197769514:regional/webacl/uplatform-waf/cd161612-4c40-49b7-86e5-64638dc18df0"
  host: qa.jp2op-project.site
