# QA environment overrides

replicaCount: 1

image:
  tag: "sha-39b26390a759584609b6ae6910537cb57fa0f067"

autoscaling:
  enabled: true
  minReplicas: 1
  maxReplicas: 3

gateway:
  certificateArn: "arn:aws:acm:ap-south-1:796197769514:certificate/ecdb468c-53a6-447c-a9e7-30a35a9e8823"
  wafAclArn: "arn:aws:wafv2:ap-south-1:796197769514:regional/webacl/uplatform-waf/ca9f4d3d-cc20-470e-891b-da07f624544c"git commit -m "chore: update cert and waf arns"

  host: qa.jp2op-project.site
