# -----------------------------------------------------------------------------
# finish.ps1 - Run this immediately after: terraform apply (in bootstrap/)
#
# Usage:
#   cd terraform/bootstrap
#   terraform apply
#   .\finish.ps1
# -----------------------------------------------------------------------------

Write-Host ""
Write-Host "Reading bootstrap outputs..." -ForegroundColor Cyan

$BUCKET        = terraform output -raw state_bucket_name
$DYNAMO        = terraform output -raw dynamodb_lock_table
$KMS           = terraform output -raw kms_key_arn
$REGION        = "ap-south-1"
$PIPELINE_ROLE = terraform output -raw terraform_pipeline_role_arn
$OIDC_ARN      = terraform output -raw github_oidc_provider_arn

# -----------------------------------------------------------------------------
# Write backend.tf
# -----------------------------------------------------------------------------

Write-Host ""
Write-Host "Writing terraform/backend.tf..." -ForegroundColor Cyan

$backendContent = @"
# Auto-generated by terraform/bootstrap/finish.ps1
# Do not edit manually.

terraform {
  backend "s3" {
    bucket         = "$BUCKET"
    key            = "state.tfstate"
    region         = "$REGION"
    dynamodb_table = "$DYNAMO"
    kms_key_id     = "$KMS"
    encrypt        = true
  }
}
"@

$backendContent | Out-File -FilePath "..\backend.tf" -Encoding utf8 -NoNewline
Write-Host "  backend.tf written" -ForegroundColor Green

# -----------------------------------------------------------------------------
# Print what to add to terraform.tfvars
# -----------------------------------------------------------------------------

Write-Host ""
Write-Host "================================================================" -ForegroundColor Yellow
Write-Host "  Add this to terraform/terraform.tfvars" -ForegroundColor Yellow
Write-Host "================================================================" -ForegroundColor Yellow
Write-Host ""
Write-Host "  github_oidc_provider_arn = `"$OIDC_ARN`""
Write-Host ""

# -----------------------------------------------------------------------------
# Print GitHub secrets
# -----------------------------------------------------------------------------

Write-Host "================================================================" -ForegroundColor Yellow
Write-Host "  Add these as GitHub Actions secrets" -ForegroundColor Yellow
Write-Host "  repo -> Settings -> Secrets and variables -> Actions -> New secret" -ForegroundColor Yellow
Write-Host "================================================================" -ForegroundColor Yellow
Write-Host ""
Write-Host "  Name:  TF_PIPELINE_ROLE_ARN"
Write-Host "  Value: $PIPELINE_ROLE"
Write-Host ""
Write-Host "  Name:  AWS_REGION"
Write-Host "  Value: $REGION"
Write-Host ""

# -----------------------------------------------------------------------------
# Print next steps
# -----------------------------------------------------------------------------

Write-Host "================================================================" -ForegroundColor Yellow
Write-Host "  Next steps" -ForegroundColor Yellow
Write-Host "================================================================" -ForegroundColor Yellow
Write-Host ""
Write-Host "  1. Add github_oidc_provider_arn to terraform/terraform.tfvars"
Write-Host "  2. Add the two GitHub secrets above in the GitHub UI"
Write-Host "  3. Add .gitignore to terraform/ (see docs)"
Write-Host "  4. git add terraform/backend.tf terraform/terraform.tfvars"
Write-Host "  5. git commit -m 'chore: configure terraform backend'"
Write-Host "  6. git push -> pipeline triggers automatically"
Write-Host ""