# Auto-generated by terraform/bootstrap/finish.ps1
# Do not edit manually.

terraform {
  backend "s3" {
    bucket         = "uplat-tf-state-796197769514"
    key            = "state.tfstate"
    region         = "ap-south-1"
    dynamodb_table = "uplat-tf-lock"
    kms_key_id     = "arn:aws:kms:ap-south-1:796197769514:key/ffcb8d98-c70c-45b3-b669-7dce1d6cc596"
    encrypt        = true
  }
}