{{- if .Values.dbInit.enabled }}
apiVersion: external-secrets.io/v1beta1
kind: ExternalSecret
metadata:
  name: {{ .Values.dbInit.rootSecretRef }}
  labels:
    {{- include "backend.labels" . | nindent 4 }}
  annotations:
    argocd.argoproj.io/hook: PreSync
    argocd.argoproj.io/sync-wave: "-2"
spec:
  refreshInterval: 24h

  secretStoreRef:
    name: aws-secrets-manager
    kind: SecretStore

  target:
    name: {{ .Values.dbInit.rootSecretRef }}
    creationPolicy: Owner

  data:
    - secretKey: password
      remoteRef:
        key: {{ .Values.dbInit.rootSecretName }}
        property: password
    - secretKey: host
      remoteRef:
        key: {{ .Values.dbInit.rootSecretName }}
        property: host
    - secretKey: db_name
      remoteRef:
        key: {{ .Values.externalSecret.secretName }}
        property: MYSQL_DATABASE
    - secretKey: db_user
      remoteRef:
        key: {{ .Values.externalSecret.secretName }}
        property: MYSQL_USER
    - secretKey: db_password
      remoteRef:
        key: {{ .Values.externalSecret.secretName }}
        property: MYSQL_PASSWORD
{{- end }}