apiVersion: external-secrets.io/v1beta1
kind: SecretStore
metadata:
  name: aws-secrets-manager
  labels:
    {{- include "backend.labels" . | nindent 4 }}
  annotations:
    argocd.argoproj.io/hook: PreSync
    argocd.argoproj.io/sync-wave: "-3"
    argocd.argoproj.io/hook-delete-policy: Never
spec:
  provider:
    aws:
      service: SecretsManager
      region: {{ .Values.secretStore.region }}
      auth:
        jwt:
          serviceAccountRef:
            name: {{ .Values.eso.serviceAccountName }}