apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: backend-prod
  namespace: argocd
  finalizers:
    - resources-finalizer.argocd.argoproj.io
spec:
  project: default
  source:
    repoURL: https://github.com/Jp2op/user-platform-project-V2
    targetRevision: main
    path: charts/backend
    helm:
      releaseName: backend
      valueFiles:
        - values.yaml
        - values-prod.yaml
  destination:
    server: https://kubernetes.default.svc
    namespace: prod
  # No automated sync — PROD requires manual sync in ArgoCD UI
  syncPolicy:
    syncOptions:
      - CreateNamespace=false
      - ServerSideApply=true
